---
  - name: This playbook will install Apache
    yum: name={{ item }} state=latest
    with_items: "{{ app_install }}"

  - name: This will copy index.html file
    copy: src=* dest=/var/www/html/index.html
    notify: start apache
