---
  - name: This playbook will install Apache
    yum: name={{item}} state=latest
    with_items: "{{app_install}}"
    tags: apache_install

  - name: This will copy index.html file
    copy: src=/udata/file.index.html dest=/var/www/html/index.html
    tags: copy_file
    notify: start apache
