---
  - name: This playbook will install Apache
    yum: name={{app_install}} state=latest
    #with_items: "{{app_install}}"
    tags: apache_install

  - name: This will copy index.html file
    copy: src=/udata/file/index.html dest=/var/www/html/index.html
    notify: start apache
    tags: copy_file
